#1 1 tom 2 bob
name1=input('enter the name of person one')
name2=input('enter secon persons name')
#task 2 3 mary 4 john
name3=input("say your name please")
print("nice to meet you mary..." + name3)
name4=input("say your name")
print("nice to meet you john..." + name4)
#task 3 name ramaz last name moseshvilli age 41 wants:create  a app about his work 
name=input('enter the  name ')
last_name=input('enter your last name!')
age=input("enter your age  please ")
wants=input("enter what do u want?")

print(name + last_name+age+wants)