#writing a proposal
name="hello my name is sali"
last_name="my lastname is moseshvili"
age="i am 10 years old"
family="i live with my mom dad and brother"
country="i am form georgia"
friends="i found new friend her name is anna she is from group 40 she is 15 years old"
print(name,last_name,age,family,country,friends)
#start math
print(90+368) #1
print(8492-931) #2
print(5*5) #3
print(90**5) #4
print(486/8) #5
print(9000//3) #6

print(284557+8200)#7
print(80475-1290)#8
print(75*5)#9
print(8747/9)#10
print(848872//290)#11
print(7496**4321)#12

print(8140+8196)#13
print(84998-284)#14
print(8902*90)#15
print(54**4)#16
print(945210/9)#17
print(274890//84)#18

print(80+21)#19
print(40-20)#20
print(980*9)#21
print(8911**210)#22
print(80/9)#23
print(8210//80)#24